- App/Redux/ScheduleRedux.js
- App/Sagas/ScheduleSagas.js
- App/Sagas/ScheduleUpdateSagas.js
For speaker schedule and updating current time
> Clean up action names and noise in sagas

- App/Containers/BreakDetailScreen.js
- App/Containers/Styles/BreakDetailScreenStyle.js
- App/Fixtures/schedule.json
- App/Redux/ScheduleRedux.js
Trello: https://trello.com/c/X9lzWTUq/4-make-lunch-coffee-break-work
Adds dynamic time and list items to BreakDetail
> Add accurate time and dynamic list data to break detail

- App/Config/AppConfig.js
For now, turn off font scaling to prevent unintended design layout anomalies...
> Turn off font scaling

- App/Components/Styles/BreakStyle.js
- App/Components/Styles/RemindMeButtonStyle.js
- App/Components/Styles/TalkInfoStyle.js
- App/Components/TalkInfo.js
- App/Containers/ScheduleScreen.js
- App/Containers/Styles/TalksScreenStyle.js
> Make responsive for iPhone 5

- App/Config/ReactotronConfig.js
- App/Containers/App.js
- App/Redux/CreateStore.js
- App/Services/Api.js
- App/Services/RehydrationServices.js
- package.json
- yarn.lock
> upgrade reactotron

- App/Containers/LocationScreen.js
- App/Redux/LocationRedux.js
- App/Redux/index.js
- App/Sagas/LocationSagas.js
- App/Sagas/StartupSagas.js
- App/Sagas/index.js
- App/Services/Api.js
- Tests/Sagas/LocationSagaTest.js
Trello: https://trello.com/c/JujcLqyr/24-make-nearby-fed-by-api-like-speakers
The "API" is still fixtures, but this sets up the Redux/Saga foundation
> Get Nearby data from API

- App/Components/Break.js
Lunch doesn't have a sponsor, only show the logo on coffee breaks.
> Remove sponsor from lunch break

- App/Fixtures/nearby.json
- App/Sagas/index.js
- App/Services/FixtureApi.js
Current list is:
Food: Deschutes Brewery, Little Big Burger, Tasty N’ Alder, Fat Head’s Brewery, Voodoo Doughnut, Salt & Straw
Coffee: Stumptown, Heart Coffee, Peet’s Coffee, Courier Coffee
Sites: Powell’s, OMSI, Japanese Garden, Pioneer Square, Waterfront Park, Chinese Garden
Will make a card for adding real images
> Actual nearby

- App/Components/Talk.js
- App/Config/ReduxPersist.js
- App/Containers/ScheduleScreen.js
- App/Containers/TalkDetailScreen.js
- App/Redux/NotificationRedux.js
https://trello.com/c/wRaO0DWn/30-persist-%22remind-me%22
https://trello.com/c/eRyu8F0M/51-wire-up-remind-me-on-details-screen-to-actually-do-something
https://trello.com/c/zez0BCjR/50-make-speaker-detail-screen-show-same-%22remind-me%22-from-master-cell
> Remember reminders between loads and actually work

- package.json
- yarn.lock
https://github.com/react-community/react-navigation/issues/1330, issue with BackAndroid yellow box is fixed in Beta 10
> Upgrade react-navigation to beta 10 (fixes BackAndroid yellow box)

- App/Sagas/SocialSagas.js
- Tests/Sagas/SocialSagasTest.js
- ios/ChainReactApp/Info.plist
Trello: https://trello.com/c/f8ubSUmM/47-have-twitter-open-in-twitter-app-if-they-have-it-installed.
> Open twitter URLs in app if installed

- App/Components/NotificationsBar.js
- App/Components/Styles/ModalStyle.js
- App/Config/ReduxPersist.js
- App/Themes/Colors.js
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
https://trello.com/c/68jNmpe5/54-android-notifications-not-working
https://trello.com/c/weDqi9UK/53-get-blurview-working-or-worked-around-for-android
> fixing Android push notifications

- App/Containers/ScheduleScreen.js
- App/Sagas/ScheduleUpdateSagas.js
https://trello.com/c/XmGR3kfW/55-yellowbox%2C-when-cleared-the-app-stops-responding.-fix
and 
https://trello.com/c/LU4jvYU0/46-android-timer-yellow-box
> Update schedule on app open, rather than background process

- App/Containers/ScheduleScreen.js
- App/Fixtures/schedule.json
Trello: https://trello.com/c/k0vHqcE3/38-add-actual-break-and-lunch-food-options
> Add real food options

- App/Fixtures/schedule.json
> updated to use new panel photo

- App/Fixtures/nearby.json
- App/Themes/Images.js
https://trello.com/c/MUtowYQC/68-get-rid-of-peets-and-use-barista-instead-image-is-in-project-and-ready
> Use barista instead of Peets

- App/Components/Gallery.js
- App/Containers/AboutScreen.js
- App/Containers/App.js
> Transition update

- App/Components/Talk.js
> social when talk is active

- App/Config/AppConfig.js
- App/Containers/ScheduleScreen.js
- App/Fixtures/schedule.json
- App/I18n/I18n.js
- App/Redux/ScheduleRedux.js
- App/Sagas/ScheduleSagas.js
https://trello.com/c/kbDmjv0E/79-chain-react-announcements-cell
https://trello.com/c/akdeUfYT/76-welcome-to-chain-react-cell
https://trello.com/c/NAVs5b3f/80-chain-react-fairewell-cell
https://trello.com/c/28NaRk4G/81-all-the-dates-are-7-17-and-7-18-but-the-conference-is-7-10-and-7-11
> Add intro, outro, fix dates and more

- App/Containers/ScheduleScreen.js
https://trello.com/c/FJ1uwETz/73-29th-minute
> remove 1 minute gaps

- App/Components/Talk.js
- App/Config/DebugConfig.js
- App/Lib/PushNotificationHelpers.js
Fixed cancel for android
https://trello.com/c/T3YSaRFL/43-cancelling-a-notification-on-android
> fixes android cancel push

- App/Components/Gallery.tsx
- App/Components/Styles/GalleryStyle.ts
- App/Config/index.js
https://trello.com/c/MMJOk5FT/77-fix-global-font-scaling-setting
https://trello.com/c/6ZNCVZCI/78-images-not-tiling-right-for-nearby-food-sights
> Fix Nearby Tiles and TextScaling

- App/Containers/ScheduleScreen.js
https://trello.com/c/w3RSLzc2/85-scrollto-1-bug
> fix negative index issue

- App/Containers/ScheduleScreen.js
Couldn't do the elegant solution so this is better than nothing
> not beautiful, but it works - fix for scroll bug

- App/Services/Api.js
Use IR Website to fetch JSON files instead of rawgit. 
https://github.com/infinitered/ir_website/pull/354
> Switch API to IR website

- App/Containers/BreakDetailScreen.js
- App/Containers/ScheduleScreen.js
- App/Containers/TalkDetailScreen.js
1. Adds back handler for Android on Break and Talk detail screens
2. Updates `eventsByDay` in schedule screen state when redux state changes
3. Omits Vegan options header when array is empty
> Misc bug fixes

- App/Components/Talk.tsx
- App/Config/index.js
- App/Containers/ScheduleScreen.js
- App/Containers/TalkDetailScreen.js
- App/Lib/SpecialButtonHelper.js
Centralize the `toggleReminder` functionality into a helper for use in `Talk` and `TalkDetailsScreen`.
Based on some groundwork by Gant.
> Fix reminder crashing

- App/Containers/LocationScreen.js
- App/Themes/Metrics.js
Addresses https://trello.com/c/KdvF3Elt/70-android-width-bug-see-screenshot
> Update locationBackgroundHeight to be relative to screenHeight

- App/Components/Break.tsx
- App/Containers/BreakDetailScreen.js
All caps -> Capitalized
Addresses: https://trello.com/c/z1u4rO51/117-change-the-break-party-designs-to-be-capitalized-only-not-all-caps
> Update break title case

- App/Components/Announcement.tsx
- App/Components/ConferenceAnnouncements.tsx
> Re-place Squarespace logo on Announcement

- App/Components/ConferenceAnnouncements.tsx
> Set announcement width

- App/Containers/LocationScreen.js
This resolves the concern placed by @jamonholmgren 
tested on iPhone 6 and iPhone 7 plus
> map grows to fit screen

- App/Containers/BreakDetailScreen.js
- App/Navigation/ReduxNavigation.js
this works like Shawni wants the back button to work
> Back button fully fixed ANDROID

- App/Fixtures/schedule.json
> Add space to React Native on Chris Ball title

- App/Components/SeeProcess.tsx
> update link for behind the scenes

- App/Containers/AboutScreen.js
announcements were busy/noisy in about screen.  This cleans them up
> simplify announcements

- App/Components/Talk.tsx
- package.json
- yarn.lock
> add fade in for remote images

- App/Components/Break.tsx
- App/Containers/ScheduleScreen.js
> Show times on special event cell instead of float numbers

- App/Containers/BreakDetailScreen.js
- App/Containers/TalkDetailScreen.js
Add `hitSlop` of 20 to top, right, & bottom of back button.
> Increase hitSlop on back buttons for break and talk details screen

- App/Fixtures/schedule.json
Both days breakfast begins at 7:30am until 8:45am
> Change breakfast time to 730

- App/Components/Gallery.tsx
- App/Containers/LocationScreen.js
- App/Fixtures/nearby.json
> now opens google place

- App/Components/LiveHelp.tsx
- App/Components/Styles/LiveHelpStyles.ts
> Add hyperlink to CoC
